--INSERT TO ROL
INSERT INTO ROL (nombre_rol) VALUES
('Admin'),
('Cliente');

--INSRT TO USUARIO
INSERT INTO USUARIO VALUES ('1005438555', 'PAOLA LUCIA', 'MARTINEZ', 'PaolaM@gmail.com', 'Paola123', 2);

--INSERT TO RESTAURANTE
INSERT INTO RESTAURANTE VALUES ('FFFFF1D', 'RESTAURANTE LA ABUELA', 'GOURMET', 
								'SAHAGUN CALLE 32', 'RESTAURANTE HOGAREÑO', 4.2);

--INSERT TO RESEÑA
INSERT INTO RESEÑA VALUES ('1005438555', 'FFFFF1D', 'EXCELENTE SEVICIO POR PARTE DE LA ABUELITA',
						  4);

--INSERT TO RESERVA
INSERT INTO RESERVA VALUES('1005438555', 'FFFFF1D', '2023/12/13', 5);

--INSERT TO RESERVA_CONFIRMADA
INSERT INTO RESERVA_CONFIRMADA (id_usuario, id_restaurante, codigo_confirmacion, 
fecha_confirmacion ) VALUES('1005438555', 'FFFFF1D', 123, '2023/12/13');